<?php

namespace AppBundle\Repository;

/**
 * AgendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgendaRepository extends \Doctrine\ORM\EntityRepository
{


// a finir avec SELECT YEAR, SELECT DAY, SELECT MONTH
public function yearAgenda()
	{
		query = $this->getEntityManager()->createQueryBuilder()
            ->select('YEAR(prod)')
            ->from('adminBundle:Product' , 'prod')
            ->getQuery();
        return $query->getOneOrNullResult();
    }
	}

}





