<?php

namespace AppBundle\Repository;

/**
 * compteRenduRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class compteRenduRepository extends \Doctrine\ORM\EntityRepository
{
}
